### ISSUE TITLE
Whether release/remove tensor interface can be supported in TIM-VX?

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/TIM-VX#413]
These are many fp16 bias tensor  when run my fp16 model, but TIM-VX/ovxlib just support fp32 bias tensor.
I want to create fp32 bias tensor and release/remove fp16 bias tensor from graph.
I can not find the release/remove tensor interface in TIM-VX.
I can find **vsi_nn_Remove_Tensor** in Ovxlib, it consist of **vsi_nn_ReleaseTensor/vsi_nn_MapRemove**.
Whether the corresponding interface(vsi_nn_Remove_Tensor or vsi_nn_ReleaseTensor/vsi_nn_MapRemove) can be exported in TIM-VX？

**Comment by sunshinemyson** [comment]
@MESeraph ,

Since vsi_nn_RemoveTensor is not declared as a public API, I'd like suggest you:
1. For constant bias tensor, create fp32 tensor for bias directly - without create fp16 tensor - the conversion can be implemented without tim-vx support.
2. For dynamic bias tensor in fp16, create a data convert node for it - no tensor can be removed until graph released.

Thanks.

**Comment by MESeraph** [comment]
Thank you!
